version: '3.1'

services:
  kubeio-wines-server:
    container_name: kubeio-wines-server
    build: ./kubeio-wineservice/
    image: kubeio-wines-server:latest
    ports:
      - 8080:8080
    networks:
      - kubeio-network
    restart: on-failure

  kubeio-search-server:
    container_name: kubeio-search-server
    build: ./kubeio-searchservice/
    image: kubeio-search-server:latest
    ports:
      - 8081:8080
    networks:
      - kubeio-network
    restart: on-failure

networks:
  kubeio-network:
    driver: bridge