server:
  port: 8080

spring:
  application:
    name: kubeio-gateway
  cloud:
    gateway:
      routes:
        - id: kubeio-wines-service
          uri: lb://kubeio-wines-service
          predicates:
            - Path=/wines-svc/**
          filters:
            - StripPrefix=1
        - id: kubeio-search-service
          uri: lb://kubeio-search-service
          predicates:
            - Path=/search-svc/**
          filters:
            - StripPrefix=1
        - id: kubeio-discovery
          uri: lb://kubeio-discovery
          predicates:
            - Path=/discovery/**
        - id: kubeio-authorization-service
          uri: lb://kubeio-authorization-service
          predicates:
            - Path=/auth-svc/**
          filters:
            - StripPrefix=1

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://kubeio-discovery:8761/eureka
    healthcheck:
      enabled: true